#!/bin/bash
#SBATCH --array 0-3
#SBATCH -p cubric-default
#SBATCH --ntasks 8
#SBATCH --out /cubric/data/c1557187/skyfall/data/video_extraction_%a.out
source activate skyfall
python /cubric/data/c1557187/skyfall/video_extraction.py -n 4 -s ${SLURM_ARRAY_TASK_ID}